### ISSUE TITLE
Support dart2js

### ISSUE THREAD

**Issue by simolus3** [simolus3/kart#3]
At the moment, our Kernel files crash dart2js:
```
The compiler crashed: NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<DartType>(Instance of 'DartTypeConverter')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      DartTypeConverter.convert (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ir/visitors.dart:569:17)
#2      JsKernelToElementMap.getDartType (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/element_map_impl.dart:904:60)
#3      LocalData.getDartType (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/locals.dart:626:33)
#4      KernelToLocalsMapImpl.getLocalType (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/locals.dart:287:35)
#5      KernelTypeGraphBuilder.visitVariableDeclaration (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/builder_kernel.dart:791:32)
#6      VariableDeclaration.accept (package:kernel/ast.dart:5292:43)
#7      KernelTypeGraphBuilder.visit (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/builder_kernel.dart:256:24)
#8      KernelTypeGraphBuilder.visitBlock (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/builder_kernel.dart:473:7)
#9      Block.accept (package:kernel/ast.dart:4519:43)
#10     KernelTypeGraphBuilder.visit (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/builder_kernel.dart:256:24)
#11     KernelTypeGraphBuilder.visitFunctionNode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/builder_kernel.dart:397:5)
#12     FunctionNode.accept (package:kernel/ast.dart:2499:38)
#13     KernelTypeGraphBuilder.visit (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/builder_kernel.dart:256:24)
#14     KernelTypeGraphBuilder.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/builder_kernel.dart:223:12)
#15     InferrerEngine._computeMemberTypeInformation (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:630:20)
#16     InferrerEngine.analyze.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:562:14)
#17     CompilerDiagnosticReporter.withCurrentElement (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:751:15)
#18     InferrerEngine.analyze (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:561:15)
#19     InferrerEngine._analyzeAllElements.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:502:38)
#20     TypeSystem.withMember (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/type_system.dart:125:11)
#21     InferrerEngine._analyzeAllElements.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:502:13)
#22     Iterable.forEach (dart:core/iterable.dart:279:30)
#23     InferrerEngine._analyzeAllElements (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:497:22)
#24     InferrerEngine.runOverAllElements (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:312:5)
#25     TypeGraphInferrer.analyzeMain (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/type_graph_inferrer.dart:68:14)
#26     GlobalTypeInferenceTask.runGlobalTypeInference.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/types.dart:176:41)
#27     CompilerTask.measure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:64:51)
#28     GlobalTypeInferenceTask.runGlobalTypeInference (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/types.dart:169:12)
#29     Compiler.performGlobalTypeInference (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:377:28)
#30     Compiler.compileFromKernel.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:420:13)
#31     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#32     Compiler.compileFromKernel (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:414:14)
#33     Compiler.runInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:255:13)
<asynchronous suspension>
#34     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:210:38)
#35     new Future.sync (dart:async/future.dart:224:31)
#36     Compiler.run.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:210:20)
#37     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#38     Compiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:207:41)
#39     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/apiimpl.dart:91:22)
#40     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#44     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#45     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#48     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

It's probably because we're not including some type information somewhere.

**Comment by simolus3** [comment]
Yup, we need to set the `staticType` on `ConditionalExpressions`.
